In [1]:
import pandas as pd
import numpy as np

In [2]:
bike_data = pd.read_csv(r'C:\Users\Ahmad Raja\Downloads\daily-bike-share.csv')

In [3]:
bike_data.head()

instant    dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  1/1/2011       1   0     1        0        6           0   
1        2  1/2/2011       1   0     1        0        0           0   
2        3  1/3/2011       1   0     1        0        1           1   
3        4  1/4/2011       1   0     1        0        2           1   
4        5  1/5/2011       1   0     1        0        3           1   

   weathersit      temp     atemp       hum  windspeed  rentals  
0           2  0.344167  0.363625  0.805833   0.160446      331  
1           2  0.363478  0.353739  0.696087   0.248539      131  
2           1  0.196364  0.189405  0.437273   0.248309      120  
3           1  0.200000  0.212122  0.590435   0.160296      108  
4           1  0.226957  0.229270  0.436957   0.186900       82

In [4]:
bike_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     731 non-null    int64  
 1   dteday      731 non-null    object 
 2   season      731 non-null    int64  
 3   yr          731 non-null    int64  
 4   mnth        731 non-null    int64  
 5   holiday     731 non-null    int64  
 6   weekday     731 non-null    int64  
 7   workingday  731 non-null    int64  
 8   weathersit  731 non-null    int64  
 9   temp        731 non-null    float64
 10  atemp       731 non-null    float64
 11  hum         731 non-null    float64
 12  windspeed   731 non-null    float64
 13  rentals     731 non-null    int64  
dtypes: float64(4), int64(9), object(1)
memory usage: 80.1+ KB


In [5]:
bike_data.shape

(731, 14)

In [6]:
bike_data.describe()

instant      season          yr        mnth     holiday     weekday  \
count  731.000000  731.000000  731.000000  731.000000  731.000000  731.000000   
mean   366.000000    2.496580    0.500684    6.519836    0.028728    2.997264   
std    211.165812    1.110807    0.500342    3.451913    0.167155    2.004787   
min      1.000000    1.000000    0.000000    1.000000    0.000000    0.000000   
25%    183.500000    2.000000    0.000000    4.000000    0.000000    1.000000   
50%    366.000000    3.000000    1.000000    7.000000    0.000000    3.000000   
75%    548.500000    3.000000    1.000000   10.000000    0.000000    5.000000   
max    731.000000    4.000000    1.000000   12.000000    1.000000    6.000000   

       workingday  weathersit        temp       atemp         hum   windspeed  \
count  731.000000  731.000000  731.000000  731.000000  731.000000  731.000000   
mean     0.683995    1.395349    0.495385    0.474354    0.627894    0.190486   
std      0.465233    0.544894    0.183051    0.162961    0.142429    0.077498   
min      0.000000    1.000000    0.059130    0.079070    0.000000    0.022392   
25%      0.000000    1.000000    0.337083    0.337842    0.520000    0.134950   
50%      1.000000    1.000000    0.498333    0.486733    0.626667    0.180975   
75%      1.000000    2.000000    0.655417    0.608602    0.730209    0.233214   
max      1.000000    3.000000    0.861667    0.840896    0.972500    0.507463   

           rentals  
count   731.000000  
mean    848.176471  
std     686.622488  
min       2.000000  
25%     315.500000  
50%     713.000000  
75%    1096.000000  
max    3410.000000

In [7]:
bike_data.describe().T

count        mean         std       min         25%         50%  \
instant     731.0  366.000000  211.165812  1.000000  183.500000  366.000000   
season      731.0    2.496580    1.110807  1.000000    2.000000    3.000000   
yr          731.0    0.500684    0.500342  0.000000    0.000000    1.000000   
mnth        731.0    6.519836    3.451913  1.000000    4.000000    7.000000   
holiday     731.0    0.028728    0.167155  0.000000    0.000000    0.000000   
weekday     731.0    2.997264    2.004787  0.000000    1.000000    3.000000   
workingday  731.0    0.683995    0.465233  0.000000    0.000000    1.000000   
weathersit  731.0    1.395349    0.544894  1.000000    1.000000    1.000000   
temp        731.0    0.495385    0.183051  0.059130    0.337083    0.498333   
atemp       731.0    0.474354    0.162961  0.079070    0.337842    0.486733   
hum         731.0    0.627894    0.142429  0.000000    0.520000    0.626667   
windspeed   731.0    0.190486    0.077498  0.022392    0.134950    0.180975   
rentals     731.0  848.176471  686.622488  2.000000  315.500000  713.000000   

                    75%          max  
instant      548.500000   731.000000  
season         3.000000     4.000000  
yr             1.000000     1.000000  
mnth          10.000000    12.000000  
holiday        0.000000     1.000000  
weekday        5.000000     6.000000  
workingday     1.000000     1.000000  
weathersit     2.000000     3.000000  
temp           0.655417     0.861667  
atemp          0.608602     0.840896  
hum            0.730209     0.972500  
windspeed      0.233214     0.507463  
rentals     1096.000000  3410.000000

In [8]:
bike_data.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
rentals       0
dtype: int64

In [9]:
type(bike_data)

pandas.core.frame.DataFrame

In [11]:
features=['season','mnth', 'holiday','weekday','workingday','weathersit','temp', 'atemp', 'hum', 'windspeed']
X = bike_data[features].values


y = bike_data['rentals'].values


print('Features:',X[:10], '\nLabels:', y[:10], sep='\n')

Features:
[[1.        1.        0.        6.        0.        2.        0.344167
  0.363625  0.805833  0.160446 ]
 [1.        1.        0.        0.        0.        2.        0.363478
  0.353739  0.696087  0.248539 ]
 [1.        1.        0.        1.        1.        1.        0.196364
  0.189405  0.437273  0.248309 ]
 [1.        1.        0.        2.        1.        1.        0.2
  0.212122  0.590435  0.160296 ]
 [1.        1.        0.        3.        1.        1.        0.226957
  0.22927   0.436957  0.1869   ]
 [1.        1.        0.        4.        1.        1.        0.204348
  0.233209  0.518261  0.0895652]
 [1.        1.        0.        5.        1.        2.        0.196522
  0.208839  0.498696  0.168726 ]
 [1.        1.        0.        6.        0.        2.        0.165
  0.162254  0.535833  0.266804 ]
 [1.        1.        0.        0.        0.        1.        0.138333
  0.116175  0.434167  0.36195  ]
 [1.        1.        0.        1.        1.        1.        

In [12]:
bike_data[features].values

array([[ 1.      ,  1.      ,  0.      , ...,  0.363625,  0.805833,
         0.160446],
       [ 1.      ,  1.      ,  0.      , ...,  0.353739,  0.696087,
         0.248539],
       [ 1.      ,  1.      ,  0.      , ...,  0.189405,  0.437273,
         0.248309],
       ...,
       [ 1.      , 12.      ,  0.      , ...,  0.2424  ,  0.752917,
         0.124383],
       [ 1.      , 12.      ,  0.      , ...,  0.2317  ,  0.483333,
         0.350754],
       [ 1.      , 12.      ,  0.      , ...,  0.223487,  0.5775  ,
         0.154846]])

In [13]:
type(X)

numpy.ndarray

In [14]:
type(y)

numpy.ndarray

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
# Split data 70%-30% into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)


# '''
# 1: training data feature
# 2: testing data feature
# 3: training data target
# 4: testing data target

In [17]:
y_test

array([ 269, 2557,   61,  563, 3160, 1313,  555, 1582,  694, 1455,  220,
        513, 1153,  894, 1275,  599, 1032,  182,  875, 1563,  595,  863,
        752,  331,  258,  217,  145,  163, 1065,  981, 1045,   54, 2512,
        736,   41,  254,  220,  539,   68,  661,  246,  439,  466, 2622,
       2454,  838, 1050, 1208,  951,  874,  569, 1807,  480,  192, 1031,
        954,  155, 1914,   93,  815,  115, 1038,  217,  253,  240,  747,
        665,  216,  413,  307,  486, 1619, 1004,  324,  991,  688,  221,
       2562,  763,  131, 2258,   43,  330,  331, 2132, 1532,  178,  558,
        518,  799,   53, 1023,  284,  562,  775,   94, 1511, 1348, 1278,
        140,  760, 1208,  773,  190,  218,  226,  673,  261, 1899, 3031,
       2135, 2345, 1462,  174,  117,  222, 1029, 1448,  502, 2806, 1401,
        968,   74,  108,  447, 1077,  983,  630,  819,  243,  888, 2795,
        269,  998, 2204, 2301,  337,  713, 1074, 1325,  259,  325,  766,
       1246,  841,  753,  639, 2080,  775,  754, 14

In [18]:
print ('Training Set: %d rows\nTest Set: %d rows' % (X_train.shape[0], X_test.shape[0]))

Training Set: 511 rows
Test Set: 220 rows


In [19]:
# Train the model
from sklearn.linear_model import LinearRegression

In [20]:
# Fit a linear regression model on the training set

model = LinearRegression().fit(X_train, y_train)

print (model)

LinearRegression()


In [21]:
import numpy as np
predictions = model.predict(X_test)

In [22]:
#predicted
print('Predicted labels: ', np.round(predictions, 0)[:10])
print('Actual labels   : ' ,y_test[:10])

Predicted labels:  [ 242. 1578.   25. 1276. 1794. 1272.  543. 1381. 1207. 2083.]
Actual labels   :  [ 269 2557   61  563 3160 1313  555 1582  694 1455]


In [23]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, predictions)
print("MSE:", mse)

rmse = np.sqrt(mse)
print("RMSE:", rmse)

r2 = r2_score(y_test, predictions)
print("R2:", r2)

MSE: 206513.54727653397
RMSE: 454.43761648496263
R2: 0.56167521669618


In [24]:
model

LinearRegression()

In [25]:
pwd

'C:\\Users\\Ahmad Raja'

In [26]:
import joblib

In [29]:
from sklearn.ensemble import RandomForestRegressor

In [33]:
 #  Save the model as a pickle file
bike_model_pkl = r'C:\Users\Ahmad Raja\Downloads\daily-bike-share.pkl'

joblib.dump(model_ran, bike_model_pkl) #writing step

['C:\\Users\\Ahmad Raja\\Downloads\\daily-bike-share.pkl']

In [34]:
# Load the model from the file
loaded_model = joblib.load(bike_model_pkl)

In [35]:
X_train[0]

array([2.      , 6.      , 0.      , 4.      , 1.      , 2.      ,
       0.628333, 0.595346, 0.688333, 0.206471])

In [36]:
bike_data.head()

instant    dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  1/1/2011       1   0     1        0        6           0   
1        2  1/2/2011       1   0     1        0        0           0   
2        3  1/3/2011       1   0     1        0        1           1   
3        4  1/4/2011       1   0     1        0        2           1   
4        5  1/5/2011       1   0     1        0        3           1   

   weathersit      temp     atemp       hum  windspeed  rentals  
0           2  0.344167  0.363625  0.805833   0.160446      331  
1           2  0.363478  0.353739  0.696087   0.248539      131  
2           1  0.196364  0.189405  0.437273   0.248309      120  
3           1  0.200000  0.212122  0.590435   0.160296      108  
4           1  0.226957  0.229270  0.436957   0.186900       82